#!/bin/bash

curl https://api.open-meteo.com/v1/forecast\?latitude\=52.5063988\&longitude\=13.2599472\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant    |  jq > berlin_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=55.6712398\&longitude\=12.5114244\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant    |  jq > copenhagen_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=69.665229\&longitude\=18.9070344\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant     | jq > tromso_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=37.7576928\&longitude\=-122.4787995\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant  | jq > san_francisco_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=48.8588255\&longitude\=2.2646352\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant     | jq > paris_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=40.6973709\&longitude\=-74.1444869\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant   | jq > new_york_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=52.2474978\&longitude\=-7.1542292\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant    |  jq > waterford_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=51.898698\&longitude\=-8.5788916\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant     | jq > cork_daily.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=52.354637\&longitude\=4.8215607\&daily\=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,precipitation_hours,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant      | jq > amsterdam_daily.json