#!/bin/bash

curl https://api.open-meteo.com/v1/forecast\?latitude\=52.5063988\&longitude\=13.2599472\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > berlin_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=55.6712398\&longitude\=12.5114244\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > copenhagen_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=69.665229\&longitude\=18.9070344\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > tromso_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=37.7576928\&longitude\=-122.4787995\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > san_francisco_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=48.8588255\&longitude\=2.2646352\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > paris_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=40.6973709\&longitude\=-74.1444869\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > new_york_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=52.2474978\&longitude\=-7.1542292\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > waterford_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=51.898698\&longitude\=-8.5788916\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > cork_hourly.json
curl https://api.open-meteo.com/v1/forecast\?latitude\=52.354637\&longitude\=4.8215607\&hourly\=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m | jq > amsterdam_hourly.json